name: Use Central Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [ master ]
permissions:
  actions: read
  contents: read
  security-events: write  # ✅ Enables SARIF upload

jobs:
  run-central-pipeline:
    uses: HydMonk/CentralSecPipeline/.github/workflows/security.yml@main
    with:
      language: 'node'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
